// Generated migrations/024_judge_registry.sql from the judge catalogue.
// 024 is the INITIAL seed only and is frozen once merged (the migration runner
// tracks applied files by name — a regenerated 024 never re-runs). Prompt
// changes reach existing deployments via syncDefaultJudges() at boot, which
// reconciles type='default' rows with the catalogue on every start. Re-run
// this script only if 024 has never shipped:
//   bun scripts/generate-judge-seed.ts > migrations/024_judge_registry.sql
import { DEFAULT_JUDGE_ROWS } from "../src/evals-engine/judge-catalogue.js";

const ROWS = DEFAULT_JUDGE_ROWS;

const TAG = "$ao_judge$";
const quote = (s: string): string => {
  if (s.includes(TAG)) throw new Error("prompt text contains the dollar-quote tag");
  return `${TAG}${s}${TAG}`;
};
const jsonb = (v: unknown): string => (v === null ? "NULL" : `${quote(JSON.stringify(v))}::jsonb`);

const lines: string[] = [];
lines.push(`-- Judge registry: the complete catalogue of judges, defaults seeded verbatim from
-- the shipped prompt sources. GENERATED by scripts/generate-judge-seed.ts — edit the
-- sources and regenerate rather than editing this file.
--
-- type='default' rows are the judges every account gets; type='custom' rows are
-- account-authored metrics (written via the judges API, never seeded here).
-- kind='code' judges are deterministic TypeScript — the row is catalogue metadata,
-- execution never reads a prompt.
-- name is the ao_session_external_evals.judge_name fan-out key; the CHECK keeps it
-- safe for the text[] literal builder in rewriteFanOutRows.

CREATE TABLE IF NOT EXISTS ao_judges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE CHECK (name ~ '^[a-z0-9_:-]+$'),
  display_name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL CHECK (type IN ('default', 'custom')),
  scope TEXT NOT NULL CHECK (scope IN ('node', 'conversation')),
  kind TEXT NOT NULL CHECK (kind IN ('llm', 'code')),
  prompt JSONB,
  config JSONB NOT NULL DEFAULT '{}',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (kind = 'code' OR prompt IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_judges_type ON ao_judges (type);
`);

for (const r of ROWS) {
  if (r.kind === "llm") {
    const p = r.prompt as { body?: unknown; output?: unknown };
    if (!p || typeof p.body !== "string" || !p.body.trim() || typeof p.output !== "string" || !p.output.trim()) {
      throw new Error(`empty prompt for ${r.name}`);
    }
  }
  lines.push(`INSERT INTO ao_judges (name, display_name, description, type, scope, kind, prompt, config)
VALUES (${quote(r.name)}, ${quote(r.display_name)}, ${quote(r.description)}, 'default', '${r.scope}', '${r.kind}', ${jsonb(r.prompt)}, ${jsonb(r.config)})
ON CONFLICT (name) DO NOTHING;
`);
}

console.log(lines.join("\n"));
