// Regenerates migrations/024_judge_registry.sql from the judge sources.
// The seed must be VERBATIM what the code ships — so it is generated by
// importing the real constants, never retyped:
//   bun scripts/generate-judge-seed.ts > migrations/024_judge_registry.sql
import {
  HALLUCINATION, VARIABLE_EXTRACTION, LOOP_DETECTION, INSTRUCTION_ADHERENCE,
  INTENT_IDENTIFICATION, OUT_HALLUCINATION, OUT_VARIABLE, OUT_LOOP,
  OUT_INSTRUCTION, OUT_INTENT,
} from "../src/evals-engine/judges/instructions.js";
import {
  VOICEMAIL, BOT, CALL_SCREENING, LOW_ENGAGEMENT, WRONG_NUMBER, DO_NOT_DISTURB,
  USER_SENTIMENT, STT, TRANSFER_CONSENT, OUT_DETECTION, OUT_SENTIMENT, OUT_STT,
  OUT_TRANSFER_CONSENT,
} from "../src/evals-engine/judges/conversation-judges.js";
import {
  CONFIG_DEFAULT_REVIEW_SYSTEM, FOCUSED_DEFECT_REVIEW_SYSTEM,
} from "../src/evals-engine/judges/variable-extraction.js";

type Row = {
  name: string; display_name: string; description: string;
  scope: "node" | "conversation"; kind: "llm" | "code";
  prompt: Record<string, unknown> | null;
  config: Record<string, unknown>;
};

const llm = (
  name: string, display_name: string, description: string,
  scope: Row["scope"], body: string, output: string, slots: string[],
  config: Record<string, unknown>, sub_prompts?: Record<string, string>,
): Row => ({
  name, display_name, description, scope, kind: "llm",
  prompt: { body, output, slots, ...(sub_prompts ? { sub_prompts } : {}) },
  config,
});

const code = (name: string, display_name: string, description: string): Row => ({
  name, display_name, description, scope: "conversation", kind: "code",
  prompt: null, config: {},
});

const ROWS: Row[] = [
  // ── node judges ─────────────────────────────────────────────────────────
  llm("instructions_adherence", "Instruction adherence",
    "Did the agent follow this node's instructions? Four-part rubric; pass/score derived in code.",
    "node", INSTRUCTION_ADHERENCE, OUT_INSTRUCTION, ["instructions", "objective"], { max_tokens: 5000 }),
  llm("intent_identification", "Intent identification",
    "Was the chosen intent the one the caller expressed? Score derived in code.",
    "node", INTENT_IDENTIFICATION, OUT_INTENT,
    ["available_intents", "chosen_intent", "system_intents"], { max_tokens: 1500 }),
  llm("variable_extraction", "Variable extraction",
    "Were the applicable variables stored with correct values? Verdict canonicalized in code after guarded review.",
    "node", VARIABLE_EXTRACTION, OUT_VARIABLE, ["expected_variables", "actual_variables"],
    { max_tokens: 3000, review_config_default_max_tokens: 600, review_focused_defect_max_tokens: 1000 },
    { review_config_default: CONFIG_DEFAULT_REVIEW_SYSTEM, review_focused_defect: FOCUSED_DEFECT_REVIEW_SYSTEM }),
  llm("hallucination", "Hallucination",
    "Did the agent state anything unsupported by the evidence sources?",
    "node", HALLUCINATION, OUT_HALLUCINATION, [], { max_tokens: 1500 }),
  llm("node_loop", "Agent looping",
    "Did the agent repeat itself without justification instead of advancing?",
    "node", LOOP_DETECTION, OUT_LOOP, [], { max_tokens: 1500 }),
  // ── conversation judges ─────────────────────────────────────────────────
  llm("voicemail_detection", "Voicemail", "Did the call reach voicemail instead of a person?",
    "conversation", VOICEMAIL, OUT_DETECTION, [], { max_tokens: 1500 }),
  llm("bot_detection", "Bot / IVR", "Was the counterparty an automated system rather than a human?",
    "conversation", BOT, OUT_DETECTION, [], { max_tokens: 1500 }),
  llm("call_screening", "Call screening", "Did an unresolved automated screening system answer?",
    "conversation", CALL_SCREENING, OUT_DETECTION, [], { max_tokens: 1500 }),
  llm("low_engagement", "Low engagement", "Did a human answer but never engage with the topic?",
    "conversation", LOW_ENGAGEMENT, OUT_DETECTION, [], { max_tokens: 1500 }),
  llm("wrong_number", "Wrong number", "Did the caller indicate they are not the intended recipient?",
    "conversation", WRONG_NUMBER, OUT_DETECTION, [], { max_tokens: 1500 }),
  llm("do_not_disturb", "Do not disturb", "Did the caller ask not to be contacted again?",
    "conversation", DO_NOT_DISTURB, OUT_DETECTION, [], { max_tokens: 1500 }),
  llm("user_sentiment", "User sentiment",
    "The caller's predominant emotional state; pass rule (not negative/confused) applied in code.",
    "conversation", USER_SENTIMENT, OUT_SENTIMENT, [], { max_tokens: 1500 }),
  llm("stt", "STT quality",
    "Speech-to-text error and recovery counts. Stored in the verdict blob; not fanned out as a row.",
    "conversation", STT, OUT_STT, [], { max_tokens: 3000 }),
  llm("transfer_consent", "Transfer consent",
    "On transferred calls only: did the caller clearly agree to the transfer first?",
    "conversation", TRANSFER_CONSENT, OUT_TRANSFER_CONSENT, [], { max_tokens: 1500 }),
  // ── code judges (execution stays in TypeScript; rows are catalogue) ─────
  code("user_never_spoke", "Caller never spoke",
    "The caller produced no turn at all. Decided in code from the transcript."),
  code("human_transfer", "Human transfer",
    "The call was handed to a human. Decided in code from the transfer:human session tag."),
];

const TAG = "$ao_judge$";
const quote = (s: string): string => {
  if (s.includes(TAG)) throw new Error("prompt text contains the dollar-quote tag");
  return `${TAG}${s}${TAG}`;
};
const jsonb = (v: unknown): string => (v === null ? "NULL" : `${quote(JSON.stringify(v))}::jsonb`);

const lines: string[] = [];
lines.push(`-- Judge registry: the complete catalogue of judges, defaults seeded verbatim from
-- the shipped prompt sources. GENERATED by scripts/generate-judge-seed.ts — edit the
-- sources and regenerate rather than editing this file.
--
-- type='default' rows are the judges every account gets; type='custom' rows are
-- account-authored metrics (written via the judges API, never seeded here).
-- kind='code' judges are deterministic TypeScript — the row is catalogue metadata,
-- execution never reads a prompt.
-- name is the ao_session_external_evals.judge_name fan-out key; the CHECK keeps it
-- safe for the text[] literal builder in rewriteFanOutRows.

CREATE TABLE IF NOT EXISTS ao_judges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE CHECK (name ~ '^[a-z0-9_:-]+$'),
  display_name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL CHECK (type IN ('default', 'custom')),
  scope TEXT NOT NULL CHECK (scope IN ('node', 'conversation')),
  kind TEXT NOT NULL CHECK (kind IN ('llm', 'code')),
  prompt JSONB,
  config JSONB NOT NULL DEFAULT '{}',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (kind = 'code' OR prompt IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_judges_type ON ao_judges (type);
`);

for (const r of ROWS) {
  if (r.kind === "llm") {
    const p = r.prompt as { body?: unknown; output?: unknown };
    if (!p || typeof p.body !== "string" || !p.body.trim() || typeof p.output !== "string" || !p.output.trim()) {
      throw new Error(`empty prompt for ${r.name}`);
    }
  }
  lines.push(`INSERT INTO ao_judges (name, display_name, description, type, scope, kind, prompt, config)
VALUES (${quote(r.name)}, ${quote(r.display_name)}, ${quote(r.description)}, 'default', '${r.scope}', '${r.kind}', ${jsonb(r.prompt)}, ${jsonb(r.config)})
ON CONFLICT (name) DO NOTHING;
`);
}

console.log(lines.join("\n"));
